//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetectFace
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGANH
    {
        public string MANGANH { get; set; }
        public string MAKH { get; set; }
        public string TENNGANH { get; set; }
    
        public virtual KHOA KHOA { get; set; }
    }
}
