//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetectFace
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEM
    {
        public string MASV { get; set; }
        public string MAMH { get; set; }
        public Nullable<double> DIEMTL { get; set; }
        public Nullable<double> DIEMGK { get; set; }
        public Nullable<double> DIEMKT1 { get; set; }
        public Nullable<double> DIEMKT2 { get; set; }
        public Nullable<int> MAHOCKY { get; set; }
    
        public virtual HOCKY HOCKY { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
