//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraCuuDiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCKY
    {
        public HOCKY()
        {
            this.DIEMs = new HashSet<DIEM>();
        }
    
        public int MAHOCKY { get; set; }
        public Nullable<int> MANIENKHOA { get; set; }
        public string HK { get; set; }
    
        public virtual ICollection<DIEM> DIEMs { get; set; }
        public virtual NIENKHOA NIENKHOA { get; set; }
    }
}
