//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraCuuDiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        public LOP()
        {
            this.MONHOCs = new HashSet<MONHOC>();
            this.SINHVIENs = new HashSet<SINHVIEN>();
        }
    
        public string MALOP { get; set; }
        public string MAKH { get; set; }
    
        public virtual KHOA KHOA { get; set; }
        public virtual ICollection<MONHOC> MONHOCs { get; set; }
        public virtual ICollection<SINHVIEN> SINHVIENs { get; set; }
    }
}
