//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraCuuDiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public SINHVIEN()
        {
            this.DIEMs = new HashSet<DIEM>();
        }
    
        public string MASV { get; set; }
        public string MANGANH { get; set; }
        public string MALOP { get; set; }
        public string HOTEN { get; set; }
        public Nullable<System.DateTime> NGSINH { get; set; }
        public string GTINH { get; set; }
        public string NOISINH { get; set; }
        public string MABACDAOTAO { get; set; }
        public string MALOAIHINHDAOTAO { get; set; }
        public int MANIENKHOA { get; set; }
        public string HINH { get; set; }
    
        public virtual BACDAOTAO BACDAOTAO { get; set; }
        public virtual ICollection<DIEM> DIEMs { get; set; }
        public virtual LOAIHINHDAOTAO LOAIHINHDAOTAO { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual NGANH NGANH { get; set; }
        public virtual NIENKHOA NIENKHOA { get; set; }
    }
}
